### ISSUE TITLE
Repo out of date

### ISSUE THREAD

**Issue by kevinvanrijn** [purpleposeidon/Factorization#12]
Hi, I cloned the repo to build a copy that doesn't crash with the latest version of OptiFine. (See: #4)

I've got everything working and building successfully but it appears that the repo hasn't been fully updated.

The 1.7 branch is missing code from 1.7.10-0.8.108 and possibly more versions back. According to the changelog textfile it hasn't been updated past 1.7.10-0.8.100.

Any chance the missing code could be added to this repo?

**Comment by purpleposeidon** [comment]
Found it: https://github.com/purpleposeidon/Factorization/tree/1.7.10-lingering
