### ISSUE TITLE
Some Blocks with incorrect Names

### ISSUE THREAD

**Issue by MiningVillains** [purpleposeidon/Factorization#19]
Some Ores and Items will get a Itemname like: 
title.factorization.ResourceBlock.SILVERBLOCK.name
title.factorization.ResourceBlock.LEADBLOCK.name
title.factorization.ResourceBlock.DARKIRONBLOCK.name
title.BlockMatcher.name
title.BlasBlock.name
all: title.factorization:ore/gravel/*.name
all: title.factorization:ore/clean/*.name
all: title.factorization:ore/crystal/*.name
all: title.factorization:ore/reduced/*.name

Will there be a fix for?

**Comment by asiekierka** [comment]
What version of Factorization are you using, and where are the "incorrect names" visible?

**Comment by MiningVillains** [comment]
Factorization-1.7.10-0.8.108 and there visible in th Inventory. 

Maybe its an other Mod thats the problem. Here is a list wich mods in the pack:
https://www.technicpack.net/modpack/mining-villains.1375721

**Comment by MiningVillains** [comment]
Youre working on a fix for it?

**Comment by asiekierka** [comment]
If I only had time to work on every fix someone asked for...

Factorization is effectively unmaintained, and 1.7.10 is about 4.5 years old by now, with most modding happening on 1.10+ for two years now. Sorry.

**Comment by MiningVillains** [comment]
Is there a repo for my version. Maybe i find someone for fixes

**Comment by asiekierka** [comment]
This one?

**Comment by MiningVillains** [comment]
For this version: Factorization-1.7.10-0.8.108

**Comment by asiekierka** [comment]
... This is the repo you're looking for?

(Granted, there have been a few fixes since 0.8.108, but they are not going to break your setup.)

**Comment by MiningVillains** [comment]
Is there a newer version that i can use on 1.7.10?

**Comment by asiekierka** [comment]
https://asie.pl/files/mods/Factorization/Factorization-1.7.10-0.8.109.jar

**Comment by MiningVillains** [comment]
thx in this version the blocks named correct!
and with this version the newest Optifineversion for 1.7.10 is working fine!
