### ISSUE TITLE
Factorization-1.7.10-0.8.107 Crash with OptiFine_1.7.10_HD_U_D6

### ISSUE THREAD

**Issue by Steelpower900** [purpleposeidon/Factorization#4]
http://pastebin.com/VK6RAPR9

**Comment by MrAmazoni** [comment]
I have the same problem.

**Comment by deusversus** [comment]
I too have this problem.

**Comment by Ushupiuck** [comment]
@purpleposeidon Any chances of seeing this fixed in a final release? I mean, I know you're not developing this anymore, but it would be neat... I always wanted to try your mod. (fps is sort of an issue for me)

**Comment by purpleposeidon** [comment]
You could probably comment out this `if` block & compile a custom build I guess? Or you could disable FZDS, but then you wouldn't have FZDS.

https://github.com/purpleposeidon/Factorization/blob/look-its-1.7-its-MIT/src/main/java/factorization/coremod/ASMTransformer.java#L99

**Comment by Ushupiuck** [comment]
okay. thanks for the info!

**Comment by asiekierka** [comment]
[07:42:24] [main/INFO] [FML]: WorldClient FZDS patch failed! The reason is not known. Minimap mods may crash, however.

**Comment by asiekierka** [comment]
This is the best we can do without access to OptiFine source code.

https://github.com/asiekierka/Factorization/commit/c161e065f7ed93b1785d5d2fd40bc07831b2a964
