### ISSUE TITLE
Pick Block from FZ not compatible with AE2

### ISSUE THREAD

**Issue by ranger135xp** [purpleposeidon/Factorization#8]
Hello,

I just wanted to mention that the pick block key command that you add to MC isn't compatible with AE2. Ordinarily, I would simply use the regular MC Pick Block key, but yours actually allows me to pick ME cables from AE2 while they are placed in the world, and that is fantastic! Where the incompatibility comes into play is when you try to force AE2 to craft items that are craft-able and already stocked. 

For example, in AE2, if I want to craft 10 of an item that I currently have 5 of, I simply middle-click (pick block) on the item and tell it how many I want. This doesn't work with the FZ Pick Block. Is that something you can fix or implement?

**Comment by purpleposeidon** [comment]
Unfortunately it's simply not possible to improve middle click in a sane way that is also compatible. I suggest binding FZ's to an alternative key; I used alt.

**Comment by ranger135xp** [comment]
Okay that works. Just know that I posted another issue where if FZ Pick Block is set to NONE and you close and open MC again, it crashes. This on can be closed.
